### ISSUE TITLE
Maximum projection of segmentation is making this difficult!

### ISSUE THREAD

**Issue by sparkerino** [gurdon-institute/Filopodyan#2]
Hi!

When I try to use Filopodyan on the test image or any of my images, it always shows all segmentations for all timepoints simultaneously, like a maximum projection. It's making it hard to evaluate the accuracy of the segmentation. I've tried on a Mac, a PC, both running 1.52i ImageJ and the most recent release of Filopodyan, 1.5. I gave it a try with 1.3 in case it is an issue with the new release but I experience the same issue. Attaching a pic so you can see for yourself. Thank you for your help, and I'm really excited to use this program!

<img width="846" alt="screen shot 2018-12-18 at 10 27 40 am" src="https://user-images.githubusercontent.com/30428353/50171618-22089c00-02b0-11e9-877a-216ad6369a61.png">

**Comment by sparkerino** [comment]
Also, it does provide an accurate table of all the segmentation and label overlays, assigned to the correct timepoint, when I go to Image>Overlay>List Elements. It just happens to display them all simultaneously.

**Comment by rb7777** [comment]
This is an annoying bug that has been opened and closed several times, thanks for letting me know it's still broken. With the help of Jean-Yves I added the [current solution](https://github.com/gurdon-institute/Filopodyan/blob/ca803544f95e286226a62b359eaa3a7fcce6cdd2/Filopodyan/src/main/java/uk/ac/cam/gurdon/Filopodyan_.java#L166) and haven't seen the flat Overlay problem since, can you share a small data file so I can try to reproduce it?

**Comment by sparkerino** [comment]
Hi Rb,

I am seeing the issue with the example growth cone file provided with the package  as well as with my own, less pretty, data. I also checked that the version of Filopodyan_.java that I have matches the fixed version that you just linked to, and it does (at least the region of code that was highlighted, lines 165-174).

Sara

**Comment by sparkerino** [comment]
Oh hey! It's working! So what I did was, I had told Fiji to use Filopodyan on Manage Update Sites. I unselected that, re-installed from just the most recent jar file 1.2.5, and now no more overlay issue on your growth cone example! Maybe when it pulls installation instructions from update sites, it's still referring to a funky piece of code.

**Comment by rb7777** [comment]
Hi Sara,

Nice catch, the update site is still using the published version which 
doesn't include the fix we added for NEUBIAS. I'll update it, have fun 
with your filopodia!

Richard

**Comment by rb7777** [comment]
Ok, the update site is updated.
