### ISSUE TITLE
Measuring length of segmented cell body

### ISSUE THREAD

**Issue by KatyRoq** [gurdon-institute/Filopodyan#3]
Hello, Thanks for the useful software! 

I need to record the length and area of the segmented cell body. Since this value is not in the default readout, can you suggest how to measure this?

Thank you,
Katy

**Comment by rb7777** [comment]
Body area is straightforward to add. What length do you need? Perimeter length, Feret's diameter or major axis of a fitted oval are easily available in ImageJ.

Richard

**Comment by KatyRoq** [comment]
Thank you. I have been exporting all the output into the ROI manager and manually taking the measurement from the proper item. But could you perhaps point me to the correct location in the code to add the perimeter measurement? Thank you!

**Comment by rb7777** [comment]
I've added body area and perimeter length to the body table in [v1.3.2](https://github.com/gurdon-institute/Filopodyan/releases/tag/v1.3.2).
See [Filopodyan_.java 407-408](https://github.com/gurdon-institute/Filopodyan/blob/f55fdeb3a5b18fec4af1130e7003a68227fd37c8/Filopodyan/src/main/java/uk/ac/cam/gurdon/Filopodyan_.java#L407-L408)

**Comment by KatyRoq** [comment]
Excellent, Thank you so much!!
