### ISSUE TITLE
Adding a centered line

### ISSUE THREAD

**Issue by m-gebelein** [gurdon-institute/Filopodyan#4]
Hello, thank you for providing this software. I need to add a centered line (if possible in a different color) to each of the Filopodia to be able to make further calculations concerning the bending stiffness of the filopodia. Can you suggest how this can be done?

Thank you,
Maximilian

**Comment by rb7777** [comment]
It's good to hear you're doing something interesting with Filopodyan!
I've released a [new version](https://github.com/gurdon-institute/Filopodyan/releases/tag/v1.4.0) which adds an option to the GUI in advanced mode to output process profile lines to the RoiManager. These lines are the same ones used to plot process kymographs made accessible for other calculations. They're a simplified medial axis polyline made by joining ultimate points including the process base and tip, and are shown in the image overlay.

**Comment by m-gebelein** [comment]
I already worked with the updated version. The centered line is excatly what I needed.
I'm currently working on a project on ROCS images/videos at the University of Freiburg. The goal of the project is to create a time variant model to describe the filopodia movement using the hydro dynamic beam equation from Joe Howard: Mechanics of Motor Proteins and the Cytoskeleton. To be able to solve the equation I also need all the coordinates of each point of the centered line.

Thank you in advance,
Maximilian

**Comment by rb7777** [comment]
The lines added to the Roi Manager are PolygonRois, so you can display all pixel coordinates along the currently selected line using Properties.../List coordinates. You can automate it using a macro, for example:
```
for (i=0; i<roiManager("count"); i++) {
        roiManager("Select", i);
        name = Roi.getName();
        Roi.getCoordinates(xpoints, ypoints);
        for(j=0; j<xpoints.length; j++){
            setResult(name+" X", j, xpoints[j]);
            setResult(name+" Y", j, ypoints[j]);
        }
}
```

**Comment by m-gebelein** [comment]
The newly added functionality works great. However, if branching occurs in the filopodia, the centered line is not displayed correctly, as shown in the image for filopodia 1. Can you suggest a solution to display the centered line correctly?
![Git1](https://user-images.githubusercontent.com/57041511/236893979-f33976c4-043e-4e00-b9f6-a9373f4c6f3d.jpg)

**Comment by rb7777** [comment]
Filopodyan isn't designed to handle branched processes, as you can see. In your example, it should be possible to adjust the settings to detect the two branches separately (try decreasing ED iterations) or filter out the branched process by waviness.

**Comment by m-gebelein** [comment]
Your answers you provided were really helpful. Thank you very much for the great support!
