### ISSUE TITLE
Filopodia detection

### ISSUE THREAD

**Issue by m-gebelein** [gurdon-institute/Filopodyan#6]
Hello, I am currently using this software for a project at the University of Freiburg. For my report I need to know how Filopodyan detects the edges of the cells and the filopodia and how it distinguishes between these two. I would be very grateful for a brief insight.

Thank you,
Maximilian Gebelein

**Comment by rb7777** [comment]
See Figure 1 of the paper for a description of the pipeline including cell boundary detection and separation of protrusions from the cell body: [http://jcb.rupress.org/content/216/10/3405](http://jcb.rupress.org/content/216/10/3405)
